# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      additional_dependencies: [flake8]
